
#
# This LookML file was generated by AtScale on 2022-11-09T17:13:35.169047Z
#
# AtScale engine version: 2022.2.0.11610
# AtScale DesignCenter version: 2022.2.0.19507
# AtScale version: 2022.2.0.4819
# Organization: default
# Project: BQ

connection: "jk_se_demo"
label: "BQ"


include: "/views/BQ/BQ.view.lkml"


explore: BQ {
  label: "BQ"
}

