
#
# This LookML file was generated by AtScale on 2022-11-09T18:11:07.815697Z
#
# AtScale engine version: 2022.2.0.11610
# AtScale DesignCenter version: 2022.2.0.19507
# AtScale version: 2022.2.0.4819
# Organization: default
# Project: Looker

connection: "jk_se_demo"
label: "Looker"


include: "/views/Looker/Looker.view.lkml"


explore: Looker {
  label: "Looker"
}

