
#
# This LookML file was generated by AtScale on 2022-11-09T17:16:36.726680Z
#
# AtScale engine version: 2022.2.0.11610
# AtScale DesignCenter version: 2022.2.0.19507
# AtScale version: 2022.2.0.4819
# Organization: default
# Project: Sales Insightsjmk

connection: "jk_se_demo"
label: "Sales Insightsjmk"


include: "/views/Sales_Insightsjmk/Internet_Sales_Cube.view.lkml"


explore: Internet_Sales_Cube {
  label: "Internet Sales Cube"
}

