
#
# This LookML file was generated by AtScale on 2022-11-09T17:20:52.726013Z
#
# AtScale engine version: 2022.2.0.11610
# AtScale DesignCenter version: 2022.2.0.19507
# AtScale version: 2022.2.0.4819
# Organization: default
# Project: test1

connection: "jk_se_demo"
label: "test1"


include: "/views/test1/Internet_Sales_Cube.view.lkml"

include: "/views/test1/TEST1.view.lkml"


explore: Internet_Sales_Cube {
  label: "Internet Sales Cube"
}

explore: TEST1 {
  label: "TEST1"
}

